//! Render-tap names and the per-sample tap snapshot the offline render catalog reads.

pub const TUBE_RENDER_TAP_COUNT: usize = 38;
pub const TUBE_RENDER_TAP_NAMES: [&str; TUBE_RENDER_TAP_COUNT] = [
    "excitation",
    "drive_gate",
    "effort",
    "pressure_mod",
    "embouchure_mod",
    "voicing_mod",
    "feedback",
    "reed_breath",
    "reed_delta_p",
    "reed_aperture",
    "reed_raw_flow",
    "reed_source_flow",
    "reed_output",
    "reed_radiated",
    "mouth_wave",
    "mouth_incident",
    "mouth_filtered",
    "mouth_reflection",
    "bell_incident",
    "bell_reflection",
    "bell_pressure",
    "pickup_left",
    "pickup_right",
    "pickup_pressure",
    "pickup_flow",
    "pickup_sample",
    "body_input",
    "body_output",
    "body_reaction_flow",
    "bell_radiated",
    "register_vent_flow",
    "register_vent_output",
    "body_bell_sum",
    "tube_main_output",
    "tube_final_output",
    "final_pre_gain",
    "final_post_gain",
    "final_output",
];

pub(super) const FINAL_PRE_GAIN_TAP_INDEX: usize = 35;
pub(super) const FINAL_POST_GAIN_TAP_INDEX: usize = 36;
pub(super) const FINAL_OUTPUT_TAP_INDEX: usize = 37;

#[derive(Debug, Clone, Copy, Default, PartialEq)]
pub struct TubeRenderTaps {
    pub excitation: f32,
    pub drive_gate: f32,
    pub effort: f32,
    pub pressure_mod: f32,
    pub embouchure_mod: f32,
    pub voicing_mod: f32,
    pub feedback: f32,
    pub reed_breath: f32,
    pub reed_delta_p: f32,
    pub reed_aperture: f32,
    pub reed_raw_flow: f32,
    pub reed_source_flow: f32,
    pub reed_output: f32,
    pub reed_radiated: f32,
    pub mouth_wave: f32,
    pub mouth_incident: f32,
    pub mouth_filtered: f32,
    pub mouth_reflection: f32,
    pub bell_incident: f32,
    pub bell_reflection: f32,
    pub bell_pressure: f32,
    pub pickup_left: f32,
    pub pickup_right: f32,
    pub pickup_pressure: f32,
    pub pickup_flow: f32,
    pub pickup_sample: f32,
    pub body_input: f32,
    pub body_output: f32,
    pub body_reaction_flow: f32,
    pub bell_radiated: f32,
    pub register_vent_flow: f32,
    pub register_vent_output: f32,
    pub body_bell_sum: f32,
    pub tube_main_output: f32,
    pub tube_final_output: f32,
    pub final_pre_gain: f32,
    pub final_post_gain: f32,
    pub final_output: f32,
}

impl TubeRenderTaps {
    pub fn values(self) -> [f32; TUBE_RENDER_TAP_COUNT] {
        [
            self.excitation,
            self.drive_gate,
            self.effort,
            self.pressure_mod,
            self.embouchure_mod,
            self.voicing_mod,
            self.feedback,
            self.reed_breath,
            self.reed_delta_p,
            self.reed_aperture,
            self.reed_raw_flow,
            self.reed_source_flow,
            self.reed_output,
            self.reed_radiated,
            self.mouth_wave,
            self.mouth_incident,
            self.mouth_filtered,
            self.mouth_reflection,
            self.bell_incident,
            self.bell_reflection,
            self.bell_pressure,
            self.pickup_left,
            self.pickup_right,
            self.pickup_pressure,
            self.pickup_flow,
            self.pickup_sample,
            self.body_input,
            self.body_output,
            self.body_reaction_flow,
            self.bell_radiated,
            self.register_vent_flow,
            self.register_vent_output,
            self.body_bell_sum,
            self.tube_main_output,
            self.tube_final_output,
            self.final_pre_gain,
            self.final_post_gain,
            self.final_output,
        ]
    }
}
