lindelion_plugin_shell::define_parameter_bindings! {
    binding: ParameterBinding;
    parameters: pub const PARAMETERS;
    bindings: pub(crate) const PARAMETER_BINDINGS;
    defaults {
        runtime: RuntimeParameterTarget::None,
        smoothing: None::<RuntimeSmoothing>,
    }

    ParameterInfo::continuous(MASTER_GAIN_PARAMETER_ID, "Master Gain", "dB", parameter_range!(MASTER_GAIN_DB)) => {
        path: ParameterPath::Output(OutputParameter::MasterGain),
        apply: LIVE,
        runtime: RuntimeParameterTarget::Output,
        smoothing: RuntimeSmoothing::mapped(
            SmoothedParamSpec::new(
                MASTER_GAIN_LINEAR.min,
                MASTER_GAIN_LINEAR.max,
                MASTER_GAIN_LINEAR.default,
                RUNTIME_PARAMETER_SMOOTH_MS,
                RUNTIME_PARAMETER_EPSILON,
            ),
            output_gain_from_plain,
        ),
        format: ParameterFormatter::Plain,
        editor: Some(EditorParameterBinding::knob(EditorSurfaceSlot::Master, EditorSurfaceGroup::OutputKnobs, 0, "Master")),
    },
    ParameterInfo::continuous(FILTER_CUTOFF_PARAMETER_ID, "Filter Cutoff", "Hz", parameter_range!(OUTPUT_FILTER_CUTOFF_HZ)) => {
        path: ParameterPath::Output(OutputParameter::FilterCutoff),
        apply: LIVE,
        runtime: RuntimeParameterTarget::Output,
        smoothing: RuntimeSmoothing::identity(RUNTIME_PARAMETER_SMOOTH_MS, FILTER_CUTOFF_EPSILON),
        format: ParameterFormatter::Plain,
        editor: Some(EditorParameterBinding::slider(EditorSurfaceSlot::Cutoff, EditorSurfaceGroup::OutputFilter, 0, "Cutoff")),
    },
    ParameterInfo::continuous(SATURATION_PARAMETER_ID, "Saturation", "", ParameterRange::linear(0.0, 1.0, 0.0)) => {
        path: ParameterPath::Output(OutputParameter::Saturation),
        apply: LIVE,
        runtime: RuntimeParameterTarget::Output,
        smoothing: RuntimeSmoothing::identity(RUNTIME_PARAMETER_SMOOTH_MS, RUNTIME_PARAMETER_EPSILON),
        format: ParameterFormatter::Plain,
        editor: Some(EditorParameterBinding::knob(EditorSurfaceSlot::Saturation, EditorSurfaceGroup::OutputKnobs, 2, "Saturate")),
    },
    ParameterInfo::continuous(MASTER_PAN_PARAMETER_ID, "Master Pan", "", ParameterRange::linear(-1.0, 1.0, 0.0)) => {
        path: ParameterPath::Output(OutputParameter::Pan),
        apply: LIVE,
        runtime: RuntimeParameterTarget::Output,
        smoothing: RuntimeSmoothing::identity(RUNTIME_PARAMETER_SMOOTH_MS, RUNTIME_PARAMETER_EPSILON),
        format: ParameterFormatter::Plain,
        editor: Some(EditorParameterBinding::knob(EditorSurfaceSlot::Pan, EditorSurfaceGroup::OutputKnobs, 1, "Pan")),
    },
    ParameterInfo::continuous(FILTER_RESONANCE_PARAMETER_ID, "Filter Resonance", "", parameter_range!(FILTER_RESONANCE)) => {
        path: ParameterPath::Output(OutputParameter::FilterResonance),
        apply: LIVE,
        runtime: RuntimeParameterTarget::Output,
        smoothing: RuntimeSmoothing::identity(RUNTIME_PARAMETER_SMOOTH_MS, RUNTIME_PARAMETER_EPSILON),
        format: ParameterFormatter::Plain,
        editor: Some(EditorParameterBinding::slider(EditorSurfaceSlot::Resonance, EditorSurfaceGroup::OutputFilter, 1, "Res")),
    },
    ParameterInfo::stepped(7, "Filter Mode", "", ParameterRange::linear(0.0, 2.0, 0.0), 2) => {
        path: ParameterPath::Output(OutputParameter::FilterMode),
        apply: LIVE_MUTE_RAMP,
        runtime: RuntimeParameterTarget::Output,
        format: ParameterFormatter::Label(filter_mode_label_from_plain),
        editor: Some(EditorParameterBinding::slider(EditorSurfaceSlot::FilterMode, EditorSurfaceGroup::OutputFilter, 2, "Mode")),
    },
    ParameterInfo::stepped(10, "Routing", "", ParameterRange::linear(0.0, 1.0, 0.0), 1) => {
        path: ParameterPath::RoutingMode,
        apply: LIVE_MUTE_RAMP,
        runtime: RuntimeParameterTarget::Routing,
        format: ParameterFormatter::Label(routing_label_from_plain),
        editor: Some(EditorParameterBinding::binary(EditorSurfaceSlot::Routing, EditorSurfaceGroup::Routing, 0, "Routing", "Parallel", "Series", 144.0)),
    },
    ParameterInfo::continuous(PARALLEL_MIX_A_PARAMETER_ID, "Parallel Mix A", "", ParameterRange::linear(0.0, 1.0, 0.5)) => {
        path: ParameterPath::ParallelMixA,
        apply: LIVE,
        runtime: RuntimeParameterTarget::Routing,
        smoothing: RuntimeSmoothing::identity(RUNTIME_PARAMETER_SMOOTH_MS, RUNTIME_PARAMETER_EPSILON),
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::continuous(PARALLEL_MIX_B_PARAMETER_ID, "Parallel Mix B", "", ParameterRange::linear(0.0, 1.0, 0.5)) => {
        path: ParameterPath::ParallelMixB,
        apply: LIVE,
        runtime: RuntimeParameterTarget::Routing,
        smoothing: RuntimeSmoothing::identity(RUNTIME_PARAMETER_SMOOTH_MS, RUNTIME_PARAMETER_EPSILON),
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::stepped(13, "Retrigger Resonators", "", ParameterRange::linear(0.0, 1.0, 0.0), 1) => {
        path: ParameterPath::RetriggerResonators,
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Label(retrigger_label_from_plain),
        editor: Some(EditorParameterBinding::binary(EditorSurfaceSlot::RetriggerResonators, EditorSurfaceGroup::ResonatorHeader, 0, "Retrigger", "Carry", "Retrig", 144.0)),
    },

    ParameterInfo::stepped(20, "Resonator A Model", "", ParameterRange::linear(0.0, 1.0, 0.0), 1) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::A, parameter: ResonatorParameter::Model },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Label(resonator_model_label_from_plain),
        editor: Some(EditorParameterBinding::binary(EditorSurfaceSlot::ResonatorAModel, EditorSurfaceGroup::ResonatorAHeader, 0, "Model", "Modal", "Wave", 118.0)),
    },
    ParameterInfo::stepped(21, "Resonator A Modal Preset", "", ParameterRange::linear(0.0, 6.0, 1.0), 6) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::A, parameter: ResonatorParameter::Modal(ModalParameter::Preset) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Label(modal_preset_label_from_plain),
        editor: Some(EditorParameterBinding::slider(EditorSurfaceSlot::ResonatorAPreset, EditorSurfaceGroup::ResonatorAControls, 0, "Preset")),
    },
    ParameterInfo::stepped(22, "Resonator A Mode Count", "", ParameterRange::linear(16.0, 256.0, 64.0), 240) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::A, parameter: ResonatorParameter::Modal(ModalParameter::ModeCount) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::stepped(23, "Resonator A Semitone", "st", ParameterRange::linear(-24.0, 24.0, 0.0), 48) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::A, parameter: ResonatorParameter::Modal(ModalParameter::Semitone) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::continuous(24, "Resonator A Cents", "ct", ParameterRange::linear(-100.0, 100.0, 0.0)) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::A, parameter: ResonatorParameter::Modal(ModalParameter::Cents) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::continuous(25, "Resonator A Inharmonicity", "", ParameterRange::linear(-1.0, 1.0, 0.0)) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::A, parameter: ResonatorParameter::Modal(ModalParameter::Inharmonicity) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::continuous(26, "Resonator A Brightness", "", ParameterRange::linear(0.0, 1.0, 0.5)) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::A, parameter: ResonatorParameter::Modal(ModalParameter::Brightness) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: Some(EditorParameterBinding::slider(EditorSurfaceSlot::ResonatorABrightness, EditorSurfaceGroup::ResonatorAControls, 1, "Bright")),
    },
    ParameterInfo::continuous(27, "Resonator A Decay", "s", ParameterRange::linear(0.05, 10.0, 1.0)) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::A, parameter: ResonatorParameter::Modal(ModalParameter::Decay) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: Some(EditorParameterBinding::slider(EditorSurfaceSlot::ResonatorADecay, EditorSurfaceGroup::ResonatorAControls, 2, "Decay")),
    },
    ParameterInfo::continuous(28, "Resonator A Decay Tilt", "", ParameterRange::linear(0.0, 1.0, 0.5)) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::A, parameter: ResonatorParameter::Modal(ModalParameter::DecayTilt) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::continuous(29, "Resonator A Strike Position", "", parameter_range!(STRIKE_POSITION)) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::A, parameter: ResonatorParameter::Modal(ModalParameter::StrikePosition) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::continuous(30, "Resonator A Loop Filter", "Hz", parameter_range!(WAVEGUIDE_LOOP_FILTER_CUTOFF_HZ)) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::A, parameter: ResonatorParameter::Waveguide(WaveguideParameter::LoopFilter) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::continuous(31, "Resonator A Loop Resonance", "", parameter_range!(FILTER_RESONANCE)) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::A, parameter: ResonatorParameter::Waveguide(WaveguideParameter::LoopResonance) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::continuous(32, "Resonator A Loop Gain", "", parameter_range!(WAVEGUIDE_LOOP_GAIN)) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::A, parameter: ResonatorParameter::Waveguide(WaveguideParameter::LoopGain) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::continuous(33, "Resonator A Nonlinearity", "", ParameterRange::linear(0.0, 1.0, 0.0)) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::A, parameter: ResonatorParameter::Waveguide(WaveguideParameter::Nonlinearity) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::continuous(34, "Resonator A Waveguide Position", "", parameter_range!(STRIKE_POSITION)) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::A, parameter: ResonatorParameter::Waveguide(WaveguideParameter::Position) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::stepped(35, "Resonator A Waveguide Style", "", ParameterRange::linear(0.0, 1.0, 0.0), 1) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::A, parameter: ResonatorParameter::Waveguide(WaveguideParameter::Style) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Label(waveguide_style_label_from_plain),
        editor: Some(EditorParameterBinding::binary(EditorSurfaceSlot::ResonatorAWaveguideStyle, EditorSurfaceGroup::ResonatorAHeader, 1, "Style", "String", "Tube", 118.0)),
    },
    ParameterInfo::continuous(36, "Resonator A Boundary Reflection", "", parameter_range!(TUBE_BOUNDARY.reflection)) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::A, parameter: ResonatorParameter::Waveguide(WaveguideParameter::BoundaryReflection) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: Some(EditorParameterBinding::slider(EditorSurfaceSlot::ResonatorABoundaryReflection, EditorSurfaceGroup::ResonatorAControls, 3, "Reflect")),
    },

    ParameterInfo::stepped(40, "Resonator B Model", "", ParameterRange::linear(0.0, 1.0, 1.0), 1) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::B, parameter: ResonatorParameter::Model },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Label(resonator_model_label_from_plain),
        editor: Some(EditorParameterBinding::binary(EditorSurfaceSlot::ResonatorBModel, EditorSurfaceGroup::ResonatorBHeader, 0, "Model", "Modal", "Wave", 118.0)),
    },
    ParameterInfo::stepped(41, "Resonator B Modal Preset", "", ParameterRange::linear(0.0, 6.0, 1.0), 6) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::B, parameter: ResonatorParameter::Modal(ModalParameter::Preset) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Label(modal_preset_label_from_plain),
        editor: None,
    },
    ParameterInfo::stepped(42, "Resonator B Mode Count", "", ParameterRange::linear(16.0, 256.0, 64.0), 240) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::B, parameter: ResonatorParameter::Modal(ModalParameter::ModeCount) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::stepped(43, "Resonator B Semitone", "st", ParameterRange::linear(-24.0, 24.0, 0.0), 48) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::B, parameter: ResonatorParameter::Modal(ModalParameter::Semitone) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::continuous(44, "Resonator B Cents", "ct", ParameterRange::linear(-100.0, 100.0, 0.0)) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::B, parameter: ResonatorParameter::Modal(ModalParameter::Cents) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::continuous(45, "Resonator B Inharmonicity", "", ParameterRange::linear(-1.0, 1.0, 0.0)) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::B, parameter: ResonatorParameter::Modal(ModalParameter::Inharmonicity) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::continuous(46, "Resonator B Brightness", "", ParameterRange::linear(0.0, 1.0, 0.5)) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::B, parameter: ResonatorParameter::Modal(ModalParameter::Brightness) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::continuous(47, "Resonator B Decay", "s", ParameterRange::linear(0.05, 10.0, 1.0)) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::B, parameter: ResonatorParameter::Modal(ModalParameter::Decay) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::continuous(48, "Resonator B Decay Tilt", "", ParameterRange::linear(0.0, 1.0, 0.5)) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::B, parameter: ResonatorParameter::Modal(ModalParameter::DecayTilt) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::continuous(49, "Resonator B Strike Position", "", parameter_range!(STRIKE_POSITION)) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::B, parameter: ResonatorParameter::Modal(ModalParameter::StrikePosition) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::continuous(50, "Resonator B Loop Filter", "Hz", parameter_range!(WAVEGUIDE_LOOP_FILTER_CUTOFF_HZ)) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::B, parameter: ResonatorParameter::Waveguide(WaveguideParameter::LoopFilter) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: Some(EditorParameterBinding::slider(EditorSurfaceSlot::ResonatorBLoopFilter, EditorSurfaceGroup::ResonatorBControls, 0, "Filter")),
    },
    ParameterInfo::continuous(51, "Resonator B Loop Resonance", "", parameter_range!(FILTER_RESONANCE)) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::B, parameter: ResonatorParameter::Waveguide(WaveguideParameter::LoopResonance) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::continuous(52, "Resonator B Loop Gain", "", parameter_range!(WAVEGUIDE_LOOP_GAIN)) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::B, parameter: ResonatorParameter::Waveguide(WaveguideParameter::LoopGain) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: Some(EditorParameterBinding::slider(EditorSurfaceSlot::ResonatorBLoopGain, EditorSurfaceGroup::ResonatorBControls, 1, "Loop")),
    },
    ParameterInfo::continuous(53, "Resonator B Nonlinearity", "", ParameterRange::linear(0.0, 1.0, 0.0)) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::B, parameter: ResonatorParameter::Waveguide(WaveguideParameter::Nonlinearity) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: Some(EditorParameterBinding::slider(EditorSurfaceSlot::ResonatorBNonlinearity, EditorSurfaceGroup::ResonatorBControls, 2, "Drive")),
    },
    ParameterInfo::continuous(54, "Resonator B Waveguide Position", "", parameter_range!(STRIKE_POSITION)) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::B, parameter: ResonatorParameter::Waveguide(WaveguideParameter::Position) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::stepped(55, "Resonator B Waveguide Style", "", ParameterRange::linear(0.0, 1.0, 0.0), 1) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::B, parameter: ResonatorParameter::Waveguide(WaveguideParameter::Style) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Label(waveguide_style_label_from_plain),
        editor: Some(EditorParameterBinding::binary(EditorSurfaceSlot::ResonatorBWaveguideStyle, EditorSurfaceGroup::ResonatorBHeader, 1, "Style", "String", "Tube", 118.0)),
    },
    ParameterInfo::continuous(56, "Resonator B Boundary Reflection", "", parameter_range!(TUBE_BOUNDARY.reflection)) => {
        path: ParameterPath::Resonator { slot: ResonatorSlot::B, parameter: ResonatorParameter::Waveguide(WaveguideParameter::BoundaryReflection) },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: Some(EditorParameterBinding::slider(EditorSurfaceSlot::ResonatorBBoundaryReflection, EditorSurfaceGroup::ResonatorBControls, 3, "Reflect")),
    },

    ParameterInfo::continuous(60, "Amp Attack", "ms", ParameterRange::linear(0.0, 5_000.0, 1.0)) => {
        path: ParameterPath::Envelope { target: EnvelopeTarget::Amp, parameter: EnvelopeParameter::Attack },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: Some(EditorParameterBinding::slider(EditorSurfaceSlot::AmpAttack, EditorSurfaceGroup::OutputEnvelope, 0, "Attack")),
    },
    ParameterInfo::continuous(61, "Amp Decay", "ms", ParameterRange::linear(0.0, 5_000.0, 80.0)) => {
        path: ParameterPath::Envelope { target: EnvelopeTarget::Amp, parameter: EnvelopeParameter::Decay },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::continuous(62, "Amp Sustain", "", ParameterRange::linear(0.0, 1.0, 1.0)) => {
        path: ParameterPath::Envelope { target: EnvelopeTarget::Amp, parameter: EnvelopeParameter::Sustain },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::continuous(63, "Amp Release", "ms", ParameterRange::linear(0.0, 10_000.0, 250.0)) => {
        path: ParameterPath::Envelope { target: EnvelopeTarget::Amp, parameter: EnvelopeParameter::Release },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: Some(EditorParameterBinding::slider(EditorSurfaceSlot::AmpRelease, EditorSurfaceGroup::OutputEnvelope, 1, "Release")),
    },
    ParameterInfo::continuous(64, "Secondary Attack", "ms", ParameterRange::linear(0.0, 5_000.0, 0.0)) => {
        path: ParameterPath::Envelope { target: EnvelopeTarget::Secondary, parameter: EnvelopeParameter::Attack },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::continuous(65, "Secondary Decay", "ms", ParameterRange::linear(0.0, 5_000.0, 250.0)) => {
        path: ParameterPath::Envelope { target: EnvelopeTarget::Secondary, parameter: EnvelopeParameter::Decay },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::continuous(66, "Secondary Sustain", "", ParameterRange::linear(0.0, 1.0, 0.0)) => {
        path: ParameterPath::Envelope { target: EnvelopeTarget::Secondary, parameter: EnvelopeParameter::Sustain },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::continuous(67, "Secondary Release", "ms", ParameterRange::linear(0.0, 10_000.0, 150.0)) => {
        path: ParameterPath::Envelope { target: EnvelopeTarget::Secondary, parameter: EnvelopeParameter::Release },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::continuous(68, "LFO Rate", "Hz", ParameterRange::linear(0.01, 100.0, 2.0)) => {
        path: ParameterPath::LfoRate,
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: Some(EditorParameterBinding::slider(EditorSurfaceSlot::LfoRate, EditorSurfaceGroup::OutputModulation, 0, "LFO")),
    },
    ParameterInfo::stepped(69, "LFO Shape", "", ParameterRange::linear(0.0, 4.0, 0.0), 4) => {
        path: ParameterPath::LfoShape,
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Label(lfo_shape_label_from_plain),
        editor: Some(EditorParameterBinding::slider(EditorSurfaceSlot::LfoShape, EditorSurfaceGroup::OutputModulation, 1, "Shape")),
    },
    ParameterInfo::stepped(70, "LFO Tempo Sync", "", ParameterRange::linear(0.0, 1.0, 0.0), 1) => {
        path: ParameterPath::LfoTempoSync,
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Label(tempo_sync_label_from_plain),
        editor: None,
    },
    ParameterInfo::continuous(71, "Pitch Bend Range", "st", ParameterRange::linear(0.0, 24.0, 2.0)) => {
        path: ParameterPath::PitchBendRange,
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::continuous(72, "Velocity Excitation", "", ParameterRange::linear(0.0, 1.0, 1.0)) => {
        path: ParameterPath::VelocityExcitationDepth,
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },

    ParameterInfo::stepped(80, "Mod 1 Enabled", "", ParameterRange::linear(0.0, 1.0, 0.0), 1) => {
        path: ParameterPath::ModulationSlot { slot: 0, parameter: ModulationSlotParameter::Enabled },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Label(enabled_label_from_plain),
        editor: Some(EditorParameterBinding::slider(EditorSurfaceSlot::Mod1Enabled, EditorSurfaceGroup::OutputModulation, 2, "Enable")),
    },
    ParameterInfo::stepped(81, "Mod 1 Source", "", ParameterRange::linear(0.0, 5.0, 2.0), 5) => {
        path: ParameterPath::ModulationSlot { slot: 0, parameter: ModulationSlotParameter::Source },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Label(format_modulation_source_label),
        editor: Some(EditorParameterBinding::slider(EditorSurfaceSlot::Mod1Source, EditorSurfaceGroup::OutputModulation, 3, "Source")),
    },
    ParameterInfo::stepped(82, "Mod 1 Destination", "", ParameterRange::linear(0.0, 6.0, 0.0), 6) => {
        path: ParameterPath::ModulationSlot { slot: 0, parameter: ModulationSlotParameter::Destination },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Label(format_modulation_destination_label),
        editor: Some(EditorParameterBinding::slider(EditorSurfaceSlot::Mod1Destination, EditorSurfaceGroup::OutputModulation, 4, "Target")),
    },
    ParameterInfo::continuous(83, "Mod 1 Amount", "", ParameterRange::linear(-1.0, 1.0, 0.0)) => {
        path: ParameterPath::ModulationSlot { slot: 0, parameter: ModulationSlotParameter::Amount },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: Some(EditorParameterBinding::slider(EditorSurfaceSlot::Mod1Amount, EditorSurfaceGroup::OutputModulation, 5, "Amount")),
    },
    ParameterInfo::stepped(84, "Mod 2 Enabled", "", ParameterRange::linear(0.0, 1.0, 0.0), 1) => {
        path: ParameterPath::ModulationSlot { slot: 1, parameter: ModulationSlotParameter::Enabled },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Label(enabled_label_from_plain),
        editor: None,
    },
    ParameterInfo::stepped(85, "Mod 2 Source", "", ParameterRange::linear(0.0, 5.0, 2.0), 5) => {
        path: ParameterPath::ModulationSlot { slot: 1, parameter: ModulationSlotParameter::Source },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Label(format_modulation_source_label),
        editor: None,
    },
    ParameterInfo::stepped(86, "Mod 2 Destination", "", ParameterRange::linear(0.0, 6.0, 0.0), 6) => {
        path: ParameterPath::ModulationSlot { slot: 1, parameter: ModulationSlotParameter::Destination },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Label(format_modulation_destination_label),
        editor: None,
    },
    ParameterInfo::continuous(87, "Mod 2 Amount", "", ParameterRange::linear(-1.0, 1.0, 0.0)) => {
        path: ParameterPath::ModulationSlot { slot: 1, parameter: ModulationSlotParameter::Amount },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::stepped(88, "Mod 3 Enabled", "", ParameterRange::linear(0.0, 1.0, 0.0), 1) => {
        path: ParameterPath::ModulationSlot { slot: 2, parameter: ModulationSlotParameter::Enabled },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Label(enabled_label_from_plain),
        editor: None,
    },
    ParameterInfo::stepped(89, "Mod 3 Source", "", ParameterRange::linear(0.0, 5.0, 2.0), 5) => {
        path: ParameterPath::ModulationSlot { slot: 2, parameter: ModulationSlotParameter::Source },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Label(format_modulation_source_label),
        editor: None,
    },
    ParameterInfo::stepped(90, "Mod 3 Destination", "", ParameterRange::linear(0.0, 6.0, 0.0), 6) => {
        path: ParameterPath::ModulationSlot { slot: 2, parameter: ModulationSlotParameter::Destination },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Label(format_modulation_destination_label),
        editor: None,
    },
    ParameterInfo::continuous(91, "Mod 3 Amount", "", ParameterRange::linear(-1.0, 1.0, 0.0)) => {
        path: ParameterPath::ModulationSlot { slot: 2, parameter: ModulationSlotParameter::Amount },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
    ParameterInfo::stepped(92, "Mod 4 Enabled", "", ParameterRange::linear(0.0, 1.0, 0.0), 1) => {
        path: ParameterPath::ModulationSlot { slot: 3, parameter: ModulationSlotParameter::Enabled },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Label(enabled_label_from_plain),
        editor: None,
    },
    ParameterInfo::stepped(93, "Mod 4 Source", "", ParameterRange::linear(0.0, 5.0, 2.0), 5) => {
        path: ParameterPath::ModulationSlot { slot: 3, parameter: ModulationSlotParameter::Source },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Label(format_modulation_source_label),
        editor: None,
    },
    ParameterInfo::stepped(94, "Mod 4 Destination", "", ParameterRange::linear(0.0, 6.0, 0.0), 6) => {
        path: ParameterPath::ModulationSlot { slot: 3, parameter: ModulationSlotParameter::Destination },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Label(format_modulation_destination_label),
        editor: None,
    },
    ParameterInfo::continuous(95, "Mod 4 Amount", "", ParameterRange::linear(-1.0, 1.0, 0.0)) => {
        path: ParameterPath::ModulationSlot { slot: 3, parameter: ModulationSlotParameter::Amount },
        apply: NOTE_BOUNDARY,
        runtime: RuntimeParameterTarget::None,
        format: ParameterFormatter::Plain,
        editor: None,
    },
}
