//! Resample Pro fidelity baseline battery (plan milestone M0).
//!
//! Renders a fixed set of controlled fixtures through the Resample Pro pitch shifter
//! at a fixed set of shifts, computes objective fidelity metrics, writes a baseline
//! table + WAV dumps under `docs/plots/data/resample_pro_fidelity/`, and sanity-asserts
//! that every metric is finite. This is the measurement foundation the later
//! milestones (M1+) are evaluated against; it is not a bug fix, so there is no
//! fail-first assertion — the verification is that the battery runs, emits the
//! baseline artifacts, and produces finite/sane numbers without regressing `make ci`.
//!
//! Real sax/wind fixture cleanliness is covered separately by `sax_fixture.rs`.

use std::fs::{File, create_dir_all};
use std::io::Write;
use std::path::PathBuf;

use lindelion_dsp_utils::analysis::{
    estimate_f0_autocorrelation, fitted_sine_rms_error, gain_fitted_rms_difference,
    high_frequency_artifact_ratio, inter_peak_floor_ratio, peak_abs, rms, shifted_frequencies,
    spectral_centroid_hz, zero_crossing_period_jitter,
};

use super::{constant_pitch_contour, envelope_peak_hz, markers};
use crate::{PitchShiftAnalysisConfig, PitchShiftAnalyzer, PitchShiftEngine, PitchShiftRatios};

const SAMPLE_RATE: u32 = 48_000;
const FIXTURE_LEN: usize = 16_000; // ~0.33 s
const METRIC_WINDOW: usize = 4_096; // fixed centered window keeps O(N^2) DFT metrics cheap

#[derive(Clone, Copy)]
struct Shift {
    label: &'static str,
    semitones: f32,
    cents: f32,
}

const SHIFTS: &[Shift] = &[
    Shift {
        label: "-12st",
        semitones: -12.0,
        cents: 0.0,
    },
    Shift {
        label: "-5st",
        semitones: -5.0,
        cents: 0.0,
    },
    Shift {
        label: "+1cent",
        semitones: 0.0,
        cents: 1.0,
    },
    Shift {
        label: "+7st",
        semitones: 7.0,
        cents: 0.0,
    },
    Shift {
        label: "+12st",
        semitones: 12.0,
        cents: 0.0,
    },
];

// On-demand baseline generator (run with `--ignored`); writes the table + WAVs and
// is the reference the later milestones are compared against. Not a per-commit gate —
// the existing `resample_pro` quality-contract tests remain the `make ci` regression
// gates — so it is excluded from the default `make ci` run to keep it fast.
#[test]
#[ignore = "baseline generator: cargo test -p lindelion-pitch-shift -- --ignored resample_pro_fidelity_baseline"]
fn resample_pro_fidelity_baseline() {
    let mut table = String::new();
    table.push_str("# Resample Pro fidelity baseline (milestone M0)\n\n");
    table.push_str(
        "Generated by `resample_pro_fidelity_baseline`. Lower dB = cleaner; ratios near 1.0 = \
         truer. Formant mode: `pres` = preserve envelope, `trk` = track pitch.\n\n",
    );
    table.push_str("| fixture | shift | formant | metric | value |\n");
    table.push_str("| --- | --- | --- | --- | --- |\n");

    let dir = output_dir();
    create_dir_all(&dir).expect("create fidelity data dir");

    // --- Tonal fixtures: pitch accuracy, phasiness (inter-partial floor), purity. ---
    let sine = sine_fixture(220.0);
    tonal_rows(&mut table, "sine220", &sine, 220.0, &[220.0], &dir);
    let stack = harmonic_stack(150.0, 8);
    let stack_partials: Vec<f32> = (1..=8).map(|h| 150.0 * h as f32).collect();
    tonal_rows(&mut table, "stack150", &stack, 150.0, &stack_partials, &dir);
    let vib = vibrato_stack(150.0, 8, 5.5, 25.0);
    tonal_rows(&mut table, "vibrato150", &vib, 150.0, &stack_partials, &dir);

    // --- Transient fixture: pre-echo + attack preservation. ---
    let (clicks, onsets) = click_train(&[2_000, 8_000, 14_000, 20_000]);
    transient_rows(&mut table, "clicks", &clicks, &onsets, &dir);

    // --- Noise fixture: alias / roughness guard. ---
    let noise = noise_fixture(0.4);
    noise_rows(&mut table, "noise", &noise, &dir);

    // --- Vowel-like formant fixture: formant tracking + brightness drift. ---
    let vowel = harmonic_stack_with_formant_local(120.0, 1_000.0);
    formant_rows(&mut table, "vowel120f1000", &vowel, 120.0, 1_000.0, &dir);

    // --- Round-trip reconstruction (up then down) on tonal fixtures. ---
    table.push_str("\n## Round-trip reconstruction (+N then -N semitones)\n\n");
    table.push_str("| fixture | semitones | reconstruction_dB |\n| --- | --- | --- |\n");
    for (label, audio, f0) in [("sine220", &sine, 220.0), ("stack150", &stack, 150.0)] {
        for semitones in [7.0_f32, 12.0] {
            let up = render(audio, f0, ratios(semitones, 0.0, false));
            let back = render(&up, f0, ratios(-semitones, 0.0, false));
            let recon = to_db(gain_fitted_rms_difference(audio, &back) / rms(audio).max(1.0e-9));
            assert!(recon.is_finite());
            table.push_str(&format!("| {label} | {semitones:+} | {recon:.1} |\n"));
        }
    }

    let mut file = File::create(dir.join("baseline.md")).expect("create baseline.md");
    file.write_all(table.as_bytes()).expect("write baseline.md");
}

fn tonal_rows(
    table: &mut String,
    name: &str,
    audio: &[f32],
    f0: f32,
    partials_hz: &[f32],
    dir: &std::path::Path,
) {
    write_wav(&dir.join(format!("{name}_source.wav")), audio);
    for shift in SHIFTS {
        let ratio =
            PitchShiftRatios::from_semitones_cents(shift.semitones, shift.cents).pitch_ratio;
        let rendered = render(audio, f0, ratios(shift.semitones, shift.cents, false));
        let steady = steady(&rendered);
        let target_f0 = f0 * ratio;
        let targets = shifted_frequencies(partials_hz, ratio);
        let floor = to_db(inter_peak_floor_ratio(steady, SAMPLE_RATE as f32, &targets));
        let hf = to_db(high_frequency_artifact_ratio(
            steady,
            SAMPLE_RATE as f32,
            target_f0,
        ));
        let jitter = zero_crossing_period_jitter(steady);
        let f0_err = f0_error_cents(steady, target_f0);
        push(table, name, shift.label, "pres", "partial_floor_dB", floor);
        push(table, name, shift.label, "pres", "hf_artifact_dB", hf);
        push(table, name, shift.label, "pres", "f0_err_cents", f0_err);
        push(table, name, shift.label, "pres", "jitter", jitter);
        if partials_hz.len() == 1 {
            let resid = to_db(
                fitted_sine_rms_error(steady, SAMPLE_RATE as f32, target_f0)
                    / rms(steady).max(1.0e-9),
            );
            push(table, name, shift.label, "pres", "sine_resid_dB", resid);
        }
        if shift.label == "+7st" {
            write_wav(&dir.join(format!("{name}_+7st.wav")), &rendered);
        }
    }
}

fn transient_rows(
    table: &mut String,
    name: &str,
    audio: &[f32],
    onsets: &[usize],
    dir: &std::path::Path,
) {
    write_wav(&dir.join(format!("{name}_source.wav")), audio);
    let source_peak = peak_abs(audio).max(1.0e-9);
    for shift in &SHIFTS[3..] {
        let rendered = render(audio, 220.0, ratios(shift.semitones, shift.cents, false));
        let pre_echo = to_db(pre_echo_ratio(&rendered, onsets));
        let peak_ratio = peak_abs(&rendered) / source_peak;
        push(table, name, shift.label, "pres", "pre_echo_dB", pre_echo);
        push(table, name, shift.label, "pres", "peak_ratio", peak_ratio);
        if shift.label == "+7st" {
            write_wav(&dir.join(format!("{name}_+7st.wav")), &rendered);
        }
    }
}

fn noise_rows(table: &mut String, name: &str, audio: &[f32], dir: &std::path::Path) {
    write_wav(&dir.join(format!("{name}_source.wav")), audio);
    for shift in &SHIFTS[3..] {
        let rendered = render(audio, 220.0, ratios(shift.semitones, shift.cents, false));
        let steady = steady(&rendered);
        let hf = to_db(high_frequency_artifact_ratio(
            steady,
            SAMPLE_RATE as f32,
            8_000.0,
        ));
        let jitter = zero_crossing_period_jitter(steady);
        push(table, name, shift.label, "pres", "hf_artifact_dB", hf);
        push(table, name, shift.label, "pres", "jitter", jitter);
        if shift.label == "+7st" {
            write_wav(&dir.join(format!("{name}_+7st.wav")), &rendered);
        }
    }
}

fn formant_rows(
    table: &mut String,
    name: &str,
    audio: &[f32],
    f0: f32,
    formant_hz: f32,
    dir: &std::path::Path,
) {
    write_wav(&dir.join(format!("{name}_source.wav")), audio);
    let source_centroid = spectral_centroid_hz(steady(audio), SAMPLE_RATE as f32).unwrap_or(0.0);
    for shift in &SHIFTS[3..] {
        for preserve in [true, false] {
            let mode = if preserve { "pres" } else { "trk" };
            let rendered = render(audio, f0, ratios(shift.semitones, shift.cents, preserve));
            let steady = steady(&rendered);
            let env_peak = output_envelope_peak_hz(&rendered, f0);
            let centroid = spectral_centroid_hz(steady, SAMPLE_RATE as f32).unwrap_or(0.0)
                / source_centroid.max(1.0);
            push(table, name, shift.label, mode, "env_peak_Hz", env_peak);
            push(table, name, shift.label, mode, "centroid_ratio", centroid);
            let _ = formant_hz;
            if shift.label == "+7st" {
                write_wav(&dir.join(format!("{name}_{mode}_+7st.wav")), &rendered);
            }
        }
    }
}

// --- Render + ratio helpers ---

fn ratios(semitones: f32, cents: f32, preserve_formant: bool) -> PitchShiftRatios {
    let pitch_ratio = PitchShiftRatios::from_semitones_cents(semitones, cents).pitch_ratio;
    PitchShiftRatios {
        pitch_ratio,
        formant_ratio: if preserve_formant {
            None
        } else {
            Some(pitch_ratio)
        },
    }
}

fn render(audio: &[f32], f0: f32, ratios: PitchShiftRatios) -> Vec<f32> {
    let contour = constant_pitch_contour(SAMPLE_RATE, f0, audio.len());
    let cache = PitchShiftAnalyzer::new(PitchShiftAnalysisConfig {
        frame_size: 4096,
        envelope_points: 128,
        ..PitchShiftAnalysisConfig::default()
    })
    .analyze(audio, SAMPLE_RATE, &contour, &markers(&[0]))
    .unwrap();
    PitchShiftEngine
        .render_resample_pro_pitch_shift(&cache, ratios)
        .unwrap()
}

fn output_envelope_peak_hz(rendered: &[f32], f0: f32) -> f32 {
    let contour = constant_pitch_contour(SAMPLE_RATE, f0, rendered.len());
    let cache = PitchShiftAnalyzer::new(PitchShiftAnalysisConfig {
        frame_size: 4096,
        envelope_points: 128,
        ..PitchShiftAnalysisConfig::default()
    })
    .analyze(rendered, SAMPLE_RATE, &contour, &markers(&[0]))
    .unwrap();
    envelope_peak_hz(&cache.frames[cache.frames.len() / 2].spectral_envelope)
}

// --- Metric helpers ---

fn steady(samples: &[f32]) -> &[f32] {
    let len = METRIC_WINDOW.min(samples.len());
    let start = samples.len().saturating_sub(len) / 2;
    &samples[start..start + len]
}

fn to_db(ratio: f32) -> f32 {
    20.0 * ratio.max(1.0e-12).log10()
}

fn f0_error_cents(samples: &[f32], target_f0: f32) -> f32 {
    estimate_f0_autocorrelation(
        samples,
        SAMPLE_RATE as f32,
        target_f0 * 0.7,
        target_f0 * 1.4,
    )
    .map(|f0| 1_200.0 * (f0 / target_f0).log2())
    .unwrap_or(f32::NAN)
}

fn pre_echo_ratio(rendered: &[f32], onsets: &[usize]) -> f32 {
    let window = 240usize; // 5 ms at 48 kHz
    let Some(&first) = onsets.first() else {
        return 0.0;
    };
    let onset = first.min(rendered.len().saturating_sub(1));
    let pre_start = onset.saturating_sub(window);
    let pre = rms(&rendered[pre_start..onset]);
    let peak = peak_abs(rendered).max(1.0e-9);
    pre / peak
}

fn push(table: &mut String, fixture: &str, shift: &str, formant: &str, metric: &str, value: f32) {
    assert!(
        value.is_finite() || value.is_nan(),
        "{fixture}/{metric} non-finite-non-nan"
    );
    table.push_str(&format!(
        "| {fixture} | {shift} | {formant} | {metric} | {value:.3} |\n"
    ));
}

// --- Fixtures ---

fn sine_fixture(f0: f32) -> Vec<f32> {
    (0..FIXTURE_LEN)
        .map(|i| (std::f32::consts::TAU * f0 * i as f32 / SAMPLE_RATE as f32).sin() * 0.6)
        .collect()
}

fn harmonic_stack(f0: f32, harmonics: usize) -> Vec<f32> {
    (0..FIXTURE_LEN)
        .map(|i| {
            (1..=harmonics)
                .map(|h| {
                    let f = f0 * h as f32;
                    (std::f32::consts::TAU * f * i as f32 / SAMPLE_RATE as f32).sin() * 0.5
                        / h as f32
                })
                .sum::<f32>()
        })
        .collect()
}

fn vibrato_stack(f0: f32, harmonics: usize, rate_hz: f32, depth_cents: f32) -> Vec<f32> {
    let mut phase = 0.0_f32;
    (0..FIXTURE_LEN)
        .map(|i| {
            let t = i as f32 / SAMPLE_RATE as f32;
            let cents = depth_cents * (std::f32::consts::TAU * rate_hz * t).sin();
            let inst_f0 = f0 * 2.0_f32.powf(cents / 1_200.0);
            phase += std::f32::consts::TAU * inst_f0 / SAMPLE_RATE as f32;
            (1..=harmonics)
                .map(|h| (phase * h as f32).sin() * 0.5 / h as f32)
                .sum::<f32>()
        })
        .collect()
}

fn click_train(onsets: &[usize]) -> (Vec<f32>, Vec<usize>) {
    let mut audio = vec![0.0_f32; FIXTURE_LEN];
    for &onset in onsets {
        // short decaying burst so it survives analysis windowing
        for k in 0..64 {
            if let Some(sample) = audio.get_mut(onset + k) {
                let env = (-(k as f32) / 12.0).exp();
                *sample +=
                    env * (std::f32::consts::TAU * 3_000.0 * k as f32 / SAMPLE_RATE as f32).sin();
            }
        }
    }
    (audio, onsets.to_vec())
}

fn noise_fixture(amplitude: f32) -> Vec<f32> {
    let mut state = 0x2545_f491_4f6c_dd1d_u64;
    (0..FIXTURE_LEN)
        .map(|_| {
            state ^= state << 13;
            state ^= state >> 7;
            state ^= state << 17;
            let normalized = (state >> 40) as f32 / (1_u32 << 24) as f32;
            (normalized * 2.0 - 1.0) * amplitude
        })
        .collect()
}

fn harmonic_stack_with_formant_local(f0: f32, formant_hz: f32) -> Vec<f32> {
    (0..FIXTURE_LEN)
        .map(|i| {
            (1..24)
                .map(|h| {
                    let f = f0 * h as f32;
                    let g = (-((f - formant_hz) / 180.0).powi(2)).exp();
                    (std::f32::consts::TAU * f * i as f32 / SAMPLE_RATE as f32).sin() * g
                })
                .sum::<f32>()
                * 0.15
        })
        .collect()
}

// --- Output ---

fn output_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("crates dir")
        .parent()
        .expect("workspace root")
        .join("docs")
        .join("plots")
        .join("data")
        .join("resample_pro_fidelity")
}

/// Minimal 16-bit PCM mono WAV writer (no external dependency).
fn write_wav(path: &std::path::Path, samples: &[f32]) {
    let data_bytes = (samples.len() * 2) as u32;
    let mut bytes: Vec<u8> = Vec::with_capacity(44 + samples.len() * 2);
    bytes.extend_from_slice(b"RIFF");
    bytes.extend_from_slice(&(36 + data_bytes).to_le_bytes());
    bytes.extend_from_slice(b"WAVE");
    bytes.extend_from_slice(b"fmt ");
    bytes.extend_from_slice(&16u32.to_le_bytes());
    bytes.extend_from_slice(&1u16.to_le_bytes()); // PCM
    bytes.extend_from_slice(&1u16.to_le_bytes()); // mono
    bytes.extend_from_slice(&SAMPLE_RATE.to_le_bytes());
    bytes.extend_from_slice(&(SAMPLE_RATE * 2).to_le_bytes()); // byte rate
    bytes.extend_from_slice(&2u16.to_le_bytes()); // block align
    bytes.extend_from_slice(&16u16.to_le_bytes()); // bits per sample
    bytes.extend_from_slice(b"data");
    bytes.extend_from_slice(&data_bytes.to_le_bytes());
    for &sample in samples {
        let value = (sample.clamp(-1.0, 1.0) * i16::MAX as f32) as i16;
        bytes.extend_from_slice(&value.to_le_bytes());
    }
    std::fs::write(path, bytes).expect("write wav");
}
