//! M3 bloom tests: drive calibration and the two cascade signatures (upward pitch
//! glide, spectral broadening) with the drive-off control arm.

use super::*;

#[test]
fn bloom_drive_calibration() {
    // M3 step 3: a full-velocity hard strike on the default voice peaks near 0.7 drive;
    // soft strikes stay essentially linear (drive ∝ amplitude², so vel 0.3 through the
    // √velocity gain lands ≈ 0.3× the full-velocity drive); the tail disengages.
    let pulse: Vec<f32> = (0..22)
        .map(|n| 0.5 * (1.0 - (std::f32::consts::TAU * n as f32 / 21.0).cos()))
        .collect();
    let render_drive = |gain: f32, samples: usize| -> (f32, f32) {
        let mut mesh = MeshResonator::new(48_000.0);
        mesh.configure(MeshVoiceParams::default());
        let mut peak_drive = 0.0_f32;
        for n in 0..samples {
            mesh.process_sample(pulse.get(n).copied().unwrap_or(0.0) * gain);
            peak_drive = peak_drive.max(mesh.tension_drive());
        }
        (peak_drive, mesh.tension_drive())
    };
    let (full_peak, full_late) = render_drive(1.0, 96_000);
    assert!(
        (0.5..=0.9).contains(&full_peak),
        "full-velocity drive peak {full_peak} outside [0.5, 0.9]"
    );
    assert!(
        full_late < 0.1,
        "drive must disengage with the tail: late={full_late}"
    );
    let (soft_peak, _) = render_drive(0.3_f32.sqrt(), 12_000);
    assert!(
        soft_peak < 0.25,
        "soft strikes must stay essentially linear: drive={soft_peak}"
    );
}

/// Frequency (Hz) of the strongest line in `[low, high]` (2 Hz scan, Hann-windowed).
fn dominant_line(samples: &[f32], low: f32, high: f32) -> f32 {
    let hann: Vec<f32> = samples
        .iter()
        .enumerate()
        .map(|(n, &v)| {
            v * (0.5 - 0.5 * (std::f32::consts::TAU * n as f32 / samples.len() as f32).cos())
        })
        .collect();
    let mut best = (low, 0.0_f32);
    let mut f = low;
    while f <= high {
        let mag = crate::plate::tests::goertzel_magnitude(&hann, f, 48_000.0);
        if mag > best.1 {
            best = (f, mag);
        }
        f += 2.0;
    }
    best.0
}

#[test]
fn bloom_produces_upward_pitch_glide() {
    // Cascade signature (a), Fletcher & Rossing: the loud-phase fundamental sits above
    // its soft-strike position (tension stiffening), within the musical gong band
    // (~5–60%, not a laser sweep).
    let pulse: Vec<f32> = (0..22)
        .map(|n| 0.5 * (1.0 - (std::f32::consts::TAU * n as f32 / 21.0).cos()))
        .collect();
    let render = |gain: f32| -> Vec<f32> {
        let mut mesh = MeshResonator::new(48_000.0);
        mesh.configure(MeshVoiceParams::default());
        (0..16_800)
            .map(|n| mesh.process_sample(pulse.get(n).copied().unwrap_or(0.0) * gain))
            .collect()
    };
    let loud = render(1.0);
    let soft = render(0.15);
    // Track the SAME physical line: locate the soft strike's fundamental, then search a
    // half-octave window above it in the loud render (the cascade reshuffles which line
    // dominates a wide band, which is line-identity switching, not glide).
    let f_soft = dominant_line(&soft[2_400..16_800], 60.0, 500.0);
    let f_loud = dominant_line(&loud[2_400..16_800], f_soft * 0.95, f_soft * 1.7);
    assert!(
        f_loud > f_soft * 1.05,
        "no upward glide: loud={f_loud} soft={f_soft}"
    );
    assert!(
        f_loud < f_soft * 1.6,
        "glide overshoots the musical band: loud={f_loud} soft={f_soft}"
    );
}

#[test]
fn bloom_broadens_the_spectrum_over_time() {
    // Cascade signature (b): with the modulation on, mid/high (2–6 kHz) energy is
    // sustained/regenerated by sum-tone generation relative to the purely decaying
    // linear plate. A/B with the drive disabled is the control arm.
    use crate::plate::PlateKernel;
    use crate::plate::spatial::SpatialWeights;
    use lindelion_dsp_utils::analysis::dft_magnitude_at;

    let layout = voice_layout(48_000.0, MeshVoiceParams::default());
    let pulse: Vec<f32> = (0..22)
        .map(|n| 0.5 * (1.0 - (std::f32::consts::TAU * n as f32 / 21.0).cos()))
        .collect();
    let render = |normalization: f32| -> Vec<f32> {
        let mut kernel = PlateKernel::new(layout.config);
        kernel.set_drive_normalization(normalization);
        kernel.set_bloom_depth(BLOOM_DEPTH);
        let grid = kernel.grid();
        let source = SpatialWeights::new(
            layout.strike,
            grid.width,
            grid.height,
            layout.excitation_width,
        );
        let pickup = SpatialWeights::point_cluster(
            layout.pickup,
            grid.width,
            grid.height,
            layout.pickup_width,
        );
        (0..21_600)
            .map(|n| {
                let force = pulse.get(n).copied().unwrap_or(0.0) * EXCITATION_FORCE_SCALE;
                kernel.process_voice_sample(force, &source, &pickup, 0.0)
            })
            .collect()
    };
    let band = |out: &[f32]| -> f32 {
        (0..17)
            .map(|n| 2_000.0 + 250.0 * n as f32)
            .map(|f| {
                let mag = dft_magnitude_at(out, 48_000.0, f);
                mag * mag
            })
            .sum::<f32>()
    };
    // The cascade GENERATES mid/high content the linear plate never has (the signature is
    // absolute band energy vs the drive-off control arm, in both the bloom window and the
    // tail; equal-length windows — unnormalized spectral magnitude scales with length).
    let linear = render(0.0);
    let bloomed = render(BLOOM_DRIVE_NORMALIZATION);
    let early = |out: &[f32]| band(&out[..7_200]);
    let late = |out: &[f32]| band(&out[9_600..16_800]);
    assert!(
        early(&bloomed) > early(&linear) * 2.0,
        "no cascade generation in the bloom window: linear={:e} bloomed={:e}",
        early(&linear),
        early(&bloomed)
    );
    assert!(
        late(&bloomed) > late(&linear) * 1.5,
        "cascade content must persist into the tail: linear={:e} bloomed={:e}",
        late(&linear),
        late(&bloomed)
    );
}

#[test]
#[ignore = "temp probe"]
fn probe_retune_raw_envelope() {
    let pulse: Vec<f32> = (0..22)
        .map(|n| 0.5 * (1.0 - (std::f32::consts::TAU * n as f32 / 21.0).cos()) * 0.9487)
        .collect();
    let mut mesh = MeshResonator::new(48_000.0);
    let notes = [220.0_f32, 261.6, 329.6, 246.9];
    let mut output = Vec::with_capacity(48_000);
    for (k, &note) in notes.iter().enumerate() {
        mesh.configure(MeshVoiceParams {
            frequency_hz: note,
            ..MeshVoiceParams::default()
        });
        for n in 0..4_800 {
            output.push(mesh.process_sample(pulse.get(n).copied().unwrap_or(0.0)));
        }
        let seg = &output[k * 4_800..(k + 1) * 4_800];
        let peak = seg.iter().fold(0.0_f32, |a, &v| a.max(v.abs()));
        eprintln!("strike {k}: raw peak={peak}");
    }
    for block in 0..6 {
        let mut peak = 0.0_f32;
        for _ in 0..12_000 {
            let v = mesh.process_sample(0.0);
            peak = peak.max(v.abs());
        }
        eprintln!("ring block {block}: raw peak={peak}");
    }
}

#[test]
fn ride_voicing_fundamental_does_not_sweep() {
    // M4 (audition defect): the bloom's DC stiffening releasing over a long ring reads as
    // a continuous downward sweep on sparse-spectrum voicings ("like a filter sweep" —
    // the Ride verdict). The fundamental may glide through the attack, but across the
    // body of the ring it must hold within 5%.
    let pulse: Vec<f32> = (0..22)
        .map(|n| 0.5 * (1.0 - (std::f32::consts::TAU * n as f32 / 21.0).cos()) * 0.9487)
        .collect();
    let mut mesh = MeshResonator::new(48_000.0);
    mesh.configure(MeshVoiceParams {
        material: 0.60,
        size: 0.50,
        damping: 0.35,
        tension: 0.45,
        strike_position: 0.72,
        pickup_spread: 0.42,
        ..MeshVoiceParams::default()
    });
    let mut output = Vec::with_capacity(96_000);
    for n in 0..96_000 {
        output.push(mesh.process_sample(pulse.get(n).copied().unwrap_or(0.0)));
    }
    // Same-line tracking: find the strongest low line late in the ring (the settled
    // pitch), then look for it near the attack within a generous upward window.
    let f_late = dominant_line(&output[57_600..96_000], 60.0, 600.0);
    let f_early = dominant_line(&output[7_200..26_400], f_late * 0.9, f_late * 1.6);
    let drift = (f_early - f_late) / f_late;
    assert!(
        drift.abs() < 0.05,
        "ride fundamental sweeps through the ring: early={f_early} late={f_late} drift={drift}"
    );
}
